#+TITLE: singularity-ubuntu-vnc-xfce

This is a singularity container of a headless [[https://releases.ubuntu.com/20.04/][Ubuntu 20.04]] with [[https://xfce.org/][Xfce desktop]].
You can access the instance via a VNC viewer or a web broswer.

* Usage
** Build
#+BEGIN_SRC shell
  sudo singularity build ubuntu-vnc-xfce.sif Singularity
#+END_SRC

But practically it's better to add several more packages to the
container before use, even if you configure conda. =Singularity.da= is
an example which adds several packages to =ubuntu-vnc-xfce.sif=.

#+BEGIN_SRC shell
  sudo singularity build ubuntu-vnc-xfce.da.sif Singularity.da
#+END_SRC

** Invoke
#+BEGIN_SRC shell
  mkdir newhome
  singularity instance start --bind $PWD/newhome:$HOME ubuntu-vnc-xfce.sif vnc
#+END_SRC

In the first run it may ask a password for the VNC connection. Port
5901 is waiting for your connection via the standard VNC
viewers. Directory =$PWD/newhome= is the home directory of the
instance; you may change it as you want.

It accepts options for =vncserver=; ex. if you would like to from the
other, then add =-localhost no=.

** Shutdown
#+BEGIN_SRC shell
  singularity instance stop vnc
#+END_SRC

** Tips
- [2022-03-21 Mon] To run this container on aarch64 (ex. through UTM
  on M1 Mac), temporarily an option
  =--env=LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1= for
  =singularity instance start= is required.
